config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root 'home#index'

  resources :comments

  resources :blogs do
    collection do
      get :my
    end
  end

end

app/models/blog.rb
class Blog < ActiveRecord::Base

  has_attached_file :blog_image, styles: { medium: "300x300>", thumb: "50x50>" }, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :blog_image, content_type: /\Aimage\/.*\Z/

  belongs_to :user
  has_many :posts, dependent: :destroy
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :user
  belongs_to :post

  scope :newest, -> { order('created_at DESC') }
end

app/models/post.rb
class Post < ActiveRecord::Base
  belongs_to :blog
  has_many :comments, dependent: :destroy

  scope :newest, -> { order('created_at DESC').limit(15) }
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :blogs, dependent: :destroy
  has_many :comments

  has_attached_file :avatar, styles: { medium: "300x300>", thumb: "50x50>" }, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\Z/

  def full_name
    "#{first_name} #{last_name}"
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_action :authenticate_user!
  before_filter :configure_devise_params, if: :devise_controller?

  def configure_devise_params
    devise_parameter_sanitizer.for(:sign_up) do |u|
      u.permit(:first_name, :last_name, :birth_date, :email, :password, :avatar)
    end
  end
end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController

  def my
    @blogs = current_user.blogs
  end

  def create
    binding.pry
    blog = current_user.blogs.create(blog_params)
    if blog.errors.blank?
      flash[:notice] = 'Post created successfully'
      redirect_to blog_path(blog)
    else
      flash[:error] = blog.errors.full_messages
      render :new
    end
  end

  def index
    @blogs = Blog.all
  end

  def show
    @blog = Blog.find(params[:id])
  end

  private

  def blog_params
    params.require(:blog).permit(:title, :desc, :blog_image)
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  respond_to :js, :html, only: :destroy

  def create
    comment = current_user.comments.create(comment_params)
    if comment.errors.blank?
      flash[:notice] = 'Post created successfully'
    else
      flash[:error] = comment.errors.full_messages
    end
    redirect_to post_path(comment_params[:post_id])
  end

  def destroy
    @comment = Comment.find(params[:id])
    post = @comment.post
    @comment.delete
    @comments = post.comments.newest
    respond_with @comment
  end

  private

  def comment_params
    params[:comment].permit!
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  skip_before_action :authenticate_user!

  def index
    @posts = Post.newest
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :get_post, only: [ :show ]

  respond_to :js, :html, only: :destroy

  def my
    @posts = current_user.posts
  end

  def create
    post = current_user.posts.create(post_params)
    if post.errors.blank?
      flash[:notice] = 'Post created successfully'
      redirect_to post_path(post)
    else
      flash[:error] = post.errors.full_messages
      render :new
    end
  end

  def destroy
    @post = Post.find(params[:id])
    user = @post.user
    @post.delete
    @posts = user.posts
    respond_with @post
  end

  private

  def post_params
    params[:post].permit!
  end

  def get_post
    @post = Post.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def navbar_type
    case params[:controller]
    when 'blogs'
      'blogs'
    else
      'home'
    end
  end
end

app/views/blogs/_blog.slim
#container.intro-effect-fadeout
  header.header
    .bg-img
      = image_tag @blog.blog_image.url, alt: 'Background Image'
    .title
      h1= @blog.title
      p.subline= @blog.desc
  br
  article.content
    div
      p We may define a food to be any substance which will repair the functional waste of the body, increase its growth, or maintain the heat, muscular, and nervous energy. </p>
      p In its most comprehensive sense, the oxygen of the air is a food; as although it is admitted by the lungs, it passes into the blood, and there re-acts upon the other food which has passed through the stomach. It is usual, however, to restrict the term food to such nutriment as enters the body by the intestinal canal. Water is often spoken of as being distinct from food, but for this there is no sufficient reason.</p>

javascript:
  (function() {

    // detect if IE : from http://stackoverflow.com/a/16657946    
    var ie = (function(){
      var undef,rv = -1; // Return value assumes failure.
      var ua = window.navigator.userAgent;
      var msie = ua.indexOf('MSIE ');
      var trident = ua.indexOf('Trident/');

      if (msie > 0) {
        // IE 10 or older => return version number
        rv = parseInt(ua.substring(msie + 5, ua.indexOf('.', msie)), 10);
      } else if (trident > 0) {
        // IE 11 (or newer) => return version number
        var rvNum = ua.indexOf('rv:');
        rv = parseInt(ua.substring(rvNum + 3, ua.indexOf('.', rvNum)), 10);
      }

      return ((rv > -1) ? rv : undef);
    }());


    // disable/enable scroll (mousewheel and keys) from http://stackoverflow.com/a/4770179          
    // left: 37, up: 38, right: 39, down: 40,
    // spacebar: 32, pageup: 33, pagedown: 34, end: 35, home: 36
    var keys = [32, 37, 38, 39, 40], wheelIter = 0;

    function preventDefault(e) {
      e = e || window.event;
      if (e.preventDefault)
      e.preventDefault();
      e.returnValue = false;  
    }

    function keydown(e) {
      for (var i = keys.length; i--;) {
        if (e.keyCode === keys[i]) {
          preventDefault(e);
          return;
        }
      }
    }

    function touchmove(e) {
      preventDefault(e);
    }

    function wheel(e) {
      // for IE 
      //if( ie ) {
        //preventDefault(e);
      //}
    }

    function disable_scroll() {
      window.onmousewheel = document.onmousewheel = wheel;
      document.onkeydown = keydown;
      document.body.ontouchmove = touchmove;
    }

    function enable_scroll() {
      window.onmousewheel = document.onmousewheel = document.onkeydown = document.body.ontouchmove = null;  
    }

    var docElem = window.document.documentElement,
      scrollVal,
      isRevealed, 
      noscroll, 
      isAnimating,
      container = document.getElementById( 'container' ),
      trigger = container.querySelector( 'button.trigger' );

    function scrollY() {
      return window.pageYOffset || docElem.scrollTop;
    }
    
    function scrollPage() {
      scrollVal = scrollY();
      
      if( noscroll && !ie ) {
        if( scrollVal < 0 ) return false;
        // keep it that way
        window.scrollTo( 0, 0 );
      }

      if( classie.has( container, 'notrans' ) ) {
        classie.remove( container, 'notrans' );
        return false;
      }

      if( isAnimating ) {
        return false;
      }
      
      if( scrollVal <= 0 && isRevealed ) {
        toggle(0);
      }
      else if( scrollVal > 0 && !isRevealed ){
        toggle(1);
      }
    }

    function toggle( reveal ) {
      isAnimating = true;
      
      if( reveal ) {
        classie.add( container, 'modify' );
      }
      else {
        noscroll = true;
        disable_scroll();
        classie.remove( container, 'modify' );
      }

      // simulating the end of the transition:
      setTimeout( function() {
        isRevealed = !isRevealed;
        isAnimating = false;
        if( reveal ) {
          noscroll = false;
          enable_scroll();
        }
      }, 600 );
    }

    // refreshing the page...
    var pageScroll = scrollY();
    noscroll = pageScroll === 0;
    
    disable_scroll();
    
    if( pageScroll ) {
      isRevealed = true;
      classie.add( container, 'notrans' );
      classie.add( container, 'modify' );
    }
    
    window.addEventListener( 'scroll', scrollPage );
    trigger.addEventListener( 'click', function() { toggle( 'reveal' ); } );
  })();

app/views/blogs/_blog_card.slim
.col.s6.m3
  .card
    .card-image
      = image_tag blog.blog_image(:medium)
      span.card-title= blog.title
    .card-content
      p= blog.desc
    .card-action
      = link_to 'View', blog

app/views/blogs/_form.slim
.row
  .col.s12.input-field
    = f.label :title
    = f.text_field :title
  .col.s12.input-field
    = f.label :desc, 'Description'
    = f.text_field :desc
  .col.s12.left-align
    = f.label :blog_image2, 'Blog image'
    br
    = f.file_field :blog_image, class: 'inputfile', id: 'blog_file'
    = f.label :file, raw('<svg xmlns="http://www.w3.org/2000/svg" width="20" height="17" viewBox="0 0 20 17"><path d="M10 0l-5.2 4.9h3.3v5.1h3.8v-5.1h3.3l-5.2-4.9zm9.3 11.5l-3.2-2.1h-2l3.4 2.6h-3.5c-.1 0-.2.1-.2.1l-.8 2.3h-6l-.8-2.2c-.1-.1-.1-.2-.2-.2h-3.6l3.4-2.6h-2l-3.2 2.1c-.4.3-.7 1-.6 1.5l.6 3.1c.1.5.7.9 1.2.9h16.3c.6 0 1.1-.4 1.3-.9l.6-3.1c.1-.5-.2-1.2-.7-1.5z"/></svg> <span>Choose a file&hellip;</span>')
button.btn.waves-effect.waves-light name="action" type="submit"
  = 'Submit'
  i.material-icons.right send

app/views/blogs/_new_blog_modal.slim
.dialog#somedialog
  .dialog__overlay
  .dialog__content
    .morph-shape
      svg height="100%" preserveaspectratio="none" viewbox=("0 0 560 280") width="100%" xmlns="http://www.w3.org/2000/svg"
        rect fill="none" height="276" width="556" x="3" y="3"
    .dialog-inner
      = form_for Blog.new do |f|
        = render 'form', f: f
      .close_dialog
        button.action data-dialog-close=""  Close

javascript:
  (function() {
    var dlgtrigger = document.querySelector( '[data-dialog]' ),
      somedialog = document.getElementById( dlgtrigger.getAttribute( 'data-dialog' ) ),
      dlg = new DialogFx( somedialog );
    dlgtrigger.addEventListener( 'click', dlg.toggle.bind(dlg) );
  })();

app/views/blogs/index.slim
h3 All blogs
.row
  .posts
    -@blogs.each do |blog|
      = render 'blog_card', blog: blog

app/views/blogs/my.slim
h3 My blogs
.row
  .posts
    -@blogs.each do |blog|
      = render 'blog_card', blog: blog

= render 'new_blog_modal'

app/views/blogs/new.slim
= form_for Blog.new do |f|
  = render 'form', f: f

app/views/blogs/show.slim
= render @blog

app/views/comments/_comment.slim
.col.s12.m4
  .card.blue-grey.darken-1
    .card-content.white-text
      = image_tag comment.user.avatar.url(:thumb), class: 'responsive-img circle'
      = comment.user.full_name
      br
      span.card-title= comment.user.full_name
      p= comment.content
    - if comment.user == current_user
      .card-action
        = link_to 'Delete Comment', comment_path(comment), method: :delete, remote: true, data: { confirm: 'Are you sure?' }, class: 'waves-effect waves-light btn'

app/views/comments/_form.slim
h5 New comment...
= simple_form_for Comment.new do |f|
  = f.input :post_id, as: :hidden, input_html: { value: post_id }
  .row
    .input-field
      = f.input :content
  = f.submit 'Create', class: 'btn'

app/views/comments/destroy.js.erb
$('.comments').html("<%= j (render @comments) %>");

app/views/home/index.slim
.asdasdasd
  p lalala!
h2 The newest blog posts!
.row
  .posts
    = render @posts

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>NewAgeBlog</title>
   <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<%= render 'shared/navbar' %>
<%= yield %>

</body>
</html>

app/views/posts/_form.slim
.input-field
  = f.input :title
.input-field
  = f.input :content
= f.submit 'Create', class: 'btn'

app/views/posts/_post.slim
.col.s12.m4
  .card.blue-grey.darken-1
    .card-content.white-text
      = image_tag post.user.avatar.url(:thumb), class: 'responsive-img circle'
      = post.user.full_name
      br
      span.card-title= post.title
      p= post.content
    - unless params[:action] == 'show'
      .card-action
          = link_to 'View', post_path(post)
          .right
            i.small.material-icons comment
            = "(#{post.comments.count})"
      - if current_user && post.user == current_user
        = link_to 'Delete', post_path(post), method: :delete, remote: true, data: { confirm: 'Are you sure?' }, class: 'waves-effect waves-light btn'

app/views/posts/destroy.js.erb
$('.posts').html("<%= j (render @posts) %>");

app/views/posts/my.slim
h3 My posts
.row
  .posts
    = render @posts

app/views/posts/new.slim
= simple_form_for Post.new do |f|
  = render 'form', f: f

app/views/posts/show.slim
= render @post
= render 'comments/form', post_id: @post.id
.comments
  = render @post.comments.newest

app/views/shared/_navbar.slim
nav
  .nav-wrapper
    = link_to 'New Age Blog', root_path, class: 'brand-logo'
    ul#nav-mobile.right.hide-on-med-and-down
      / navbar_type is a app helper method
      / please, specify new type of navbar links
      / in this method ti show your partial
      = render "shared/navbar_links/#{navbar_type}_links"
      = render 'shared/user_section'

app/views/shared/_user_section.slim
- if current_user
  li
    = image_tag current_user.avatar.url(:thumb), class: 'responsive-img circle'
    = current_user.full_name
  li
    = link_to 'Logout', destroy_user_session_path, method: :delete
- else
  li
    = link_to 'Sign in', new_user_session_path
  li
    = link_to 'Sign up', new_user_registration_path

app/views/shared/navbar_links/_blogs_links.slim
li
  .button-wrap
    = link_to 'Open Dialog', '#', 'data-dialog' => "somedialog"

app/views/shared/navbar_links/_home_links.slim
li
  = link_to 'My blogs', my_blogs_path